---
title: "shinygo_uniprot_lists"
author: "Melissa Naugle"
date: "6/2/2021"
output: html_document
---

```{r setup}
setwd("~/Desktop/GitHub/RNAseq_allsites_Barshisreference/GO/ShinyGO/")
library(tidyverse)
```


```{r}
annot <- read.csv("../../data/33496_MasterCombinedAnnotationTable.csv")

de_highvlowpollution_atcontrol <- read.csv("../../data/DE_comparison_lists/DE_control_highvlowpollution_05_14_21.csv")
de_highvlowpollution_atheat <- read.csv("../../data/DE_comparison_lists/DE_heat_highvlowpollution_06_02_21.csv")
de_heatvcontrol_atleast2sites <- read.csv("../../data/DE_comparison_lists/DE_heat_control_atleast2sites_05_14_21.csv")
de_heatvcontrol_allsites_middleofvennclassic <- read.csv("../../data/DE_comparison_lists/DE_middle_of_venn_classic_FDR0.05.csv")

de_highvlowpollution_atcontrol_annot <- annot[annot$Ourcontigname%in%de_highvlowpollution_atcontrol$ContigID,]
nrow(annot)
nrow(de_highvlowpollution_atcontrol)
nrow(de_highvlowpollution_atcontrol_annot)
de_highvlowpollution_atcontrol_annot <- de_highvlowpollution_atcontrol_annot %>% 
  select(3, 9)
write.csv(de_highvlowpollution_atcontrol_annot, "de_highvlowpollution_atcontrol_annot.csv", row.names = F)

de_highvlowpollution_atheat_annot <- annot[annot$Ourcontigname%in%de_highvlowpollution_atheat$ContigID,]
nrow(de_highvlowpollution_atheat_annot)
de_highvlowpollution_atheat_annot <- de_highvlowpollution_atheat_annot %>% 
  select(3, 9)
write.csv(de_highvlowpollution_atheat_annot, "de_highvlowpollution_atheat_annot.csv", row.names = F)


de_heatvcontrol_atleast2sites_annot<- annot[annot$Ourcontigname%in%de_heatvcontrol_atleast2sites$ContigID,]
nrow(de_heatvcontrol_atleast2sites_annot)
de_heatvcontrol_atleast2sites_annot <- de_heatvcontrol_atleast2sites_annot %>% 
  select(3, 9)
write.csv(de_heatvcontrol_atleast2sites_annot, "de_heatvcontrol_atleast2sites_annot.csv", row.names = F)


de_heatvcontrol_allsites_middleofvennclassic_annot<- annot[annot$Ourcontigname%in%de_heatvcontrol_allsites_middleofvennclassic$ContigID,]
nrow(de_heatvcontrol_allsites_middleofvennclassic_annot) #476 = correct 
de_heatvcontrol_allsites_middleofvennclassic_annot <- de_heatvcontrol_allsites_middleofvennclassic_annot %>% 
  select(3, 9)
write.csv(de_heatvcontrol_allsites_middleofvennclassic_annot, "de_heatvcontrol_allsites_middleofvennclassic_annot.csv", row.names = F)



```

