---
title: "Barshis_annot"
author: "Melissa Naugle"
date: "4/30/2021"
output: html_document
---

```{r readdata}
library("dplyr")
library("tm")
library("SnowballC")
library("wordcloud")
library("wordcloud2")
library("XML")
library("RCurl")
library("RColorBrewer")
library("ggplot2")


setwd(dir = "/Users/Melissa/Desktop/GitHub/RNAseq_allsites_Barshisreference/Scripts/")
annot <- read.csv("../data/33496_MasterCombinedAnnotationTable.csv")
head(annot)
annot$ContigID <- annot$Ourcontigname

dges_0.05 <- read.table("../data/EdgeR_P0.05/diffExpr.P0.05_C2.matrix", sep = "\t")
dges_0.05 <- cbind(ContigID = rownames(dges_0.05), dges_0.05)

```


```{r selectgenes_all}
dges_0.05_annot <- subset(annot, ContigID %in% dges_0.05$ContigID)

#to look for specific types of genes, can replace the text below 
dges_0.05_annot$topnrMatch[grep("heat", dges_0.05_annot$topnrMatch)]

write.csv(dges_0.05_annot, "../data/EdgeR_P0.05/annotations_diffExpr.P0.05_allDEgenes.csv")

```

```{r vatia_tele_controls}
vatia_fagatele <- read.csv("../data/EdgeR_P0.05/pairwise_comparisons/RSEM.isoform.counts.matrix.Ftele_H_vs_Vat_E.edgeR.DE_results.P0.05_C2.DE.subset", sep = "\t")
vatia_fagatele <- setNames(cbind(rownames(vatia_fagatele), vatia_fagatele, row.names = NULL), c("ContigID", colnames(vatia_fagatele)))
head(vatia_fagatele)
vatia_fagatele <- select(vatia_fagatele, "ContigID")

vatia_fagatele_annot <- subset(annot, ContigID %in% vatia_fagatele$ContigID)

#word cloud 
text <- vatia_fagatele_annot$Description
text <- gsub(";", " ", text)
text <- gsub("no_keywords", " ", text)
text <- gsub("keyword", " ", text)
text <- gsub("uncharacterized", " ", text)
text <- gsub("protein", " ", text)
text <- gsub("no_description", " ", text)
docs <- Corpus(VectorSource(text))
docs <- docs %>%
  tm_map(stripWhitespace) 
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)
set.seed(1234) # for reproducibility 
wordcloud(words = df$word, freq = df$freq, min.freq = 2, max.words=200, random.order=FALSE, rot.per=0.15, colors=brewer.pal(8, "Dark2"))



GOBP_vatia_fagatele_annot<- strsplit(as.character(vatia_fagatele_annot$GOBP), split = ";")

```





